service: Inviteme
package:
  excludeDevDependencies: true

provider:
  name: aws
  stage: PROD
  memorySize: 3008
  timeout: 30
  runtime: nodejs8.10
  region: ap-southeast-2
  profile: perso
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
        - 'secretsmanager:Get*'
      Resource: '*'
functions:
  addGuest:
    handler: guests/addGuest.handler
  decrypt:
    handler: crypto/decrypt.handler
  sendEmail:
    handler: mails/send.handler
